# see https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish new release of Pytarallo to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      # the second step removes the v from vX.Y.Z
      - name: Grab current version and add it to env
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${RELEASE_VERSION#?}"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Update setup.py with current version
        run: |
          echo "from setuptools import setup

                setup(
                    name='pytarallo',
                    packages=['pytarallo'],
                    version='${{ env.RELEASE_VERSION }}',
                    url='https://github.com/WEEE-Open/pytarallo',
                    download_url='https://github.com/WEEE-Open/pytarallo/archive/${{ env.RELEASE_VERSION }}.tar.gz',
                    license='MIT',
                    author='Various people',
                    author_email='weeeopen@polito.it',
                    description='Python API for the T.A.R.A.L.L.O. Inventory System',
                    keywords=['WEEEOpen', 'python-tarallo', 'T.A.R.A.L.L.O.', 'Inventory system'],
                    install_requires=['requests'],
                    extras_require={
                        'dev': ['nose', 'python-dotenv']
                    },
                    classifiers=[
                        'Development Status :: 4 - Beta',
                        'Intended Audience :: Developers',
                        'Topic :: Software Development :: Build Tools',
                        'License :: OSI Approved :: MIT License',
                        'Programming Language :: Python :: 3.6',
                    ],
                )" > setup.py

      - name: See contents of setup.py used for this release
        run: cat setup.py

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ pytarallo

# e-caste: I don't have a Test PyPI account and I don't know if it will be useful to have one,
# only publishing to the real PyPI for now
#      - name: Publish distribution ðŸ“¦ to Test PyPI
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}